server:
  port: 8081

spring:
  application:
    name: x-payment-adapter-app

  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: xpayment-adapter-request-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.iprody.common.payment.app.async.XPaymentAdapterRequestMessage
    listener:
      ack-mode: manual
      concurrency: 1

app:
  kafka:
    topics:
      xpayment-adapter:
        request: xpayment-adapter.requests
        response: xpayment-adapter.responses