services:
  payment-service-app:
    image: payment-service-app
    environment:
      SPRING_SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8085/realms/iprody-lms
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment-db
    ports:
      - "8080:8080"

  x-payment-adapter-app:
    image: x-payment-adapter-app
    environment:
      SPRING_SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      APP_X_PAYMENT_PROVIDER_API_CLIENT_URL: http://x-payment-provider-api:8080
      APP_X_PAYMENT_PROVIDER_API_CLIENT_USERNAME: paymentAgentIprody
      APP_X_PAYMENT_PROVIDER_API_CLIENT_PASSWORD: iprodyTestPassword0123
      APP_X_PAYMENT_PROVIDER_API_CLIENT_ACCOUNT: paymentAgentIprodyApiToken
      APP_X_PAYMENT_PROVIDER_API_CLIENT_X_PAY_ACCOUNT_HEADER: X-Pay-Account
    ports:
      - "8081:8080"

  x-payment-provider-api:
    image: x-payment-provider-api
    environment:
      SPRING_SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      LOGGING_LEVEL_COM_IPRODY: DEBUG
      XPAYMENT_PROCESSING_DELAY_MS: 60000
    ports:
      - "9999:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command:
      - start-dev
      - --http-port=8085
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8085"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: payment-db
      LC_MESSAGES: en_US.UTF-8
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_LOG_DIRS: /kafka/data
    volumes:
      - "./kafka_data:/kafka/data"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  rabbitmq:
    image: rabbitmq:4.2.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # для подключения клиентов к брокеру
      - "15672:15672"  # для доступа к админке
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq_delayed_message_exchange-4.2.0.ez:/plugins/rabbitmq_delayed_message_exchange.ez
    restart: unless-stopped

volumes:
  pgdata:
  kafka_data:
  rabbitmq_data:
